### ISSUE TITLE
[Solved] Unhandled Exception: HandshakeException: Handshake error in client

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/weather_app#1]
E/flutter (31854): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (31854): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))
E/flutter (31854): #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
E/flutter (31854): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
E/flutter (31854): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
E/flutter (31854): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
E/flutter (31854): <asynchronous suspension>
E/flutter (31854): #4      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:919:9)
E/flutter (31854): <asynchronous suspension>
E/flutter (31854): #5      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:13)

**Comment by kangsudal** [comment]
answer:
https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req
https://www.youtube.com/watch?v=kXlMjv0KOzg

code:
class MyHttpOverrides extends HttpOverrides{
@OverRide
HttpClient createHttpClient(SecurityContext? context){
return super.createHttpClient(context)
..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
}
}

생각:
server의 문제인거같다. 내가할 수 있는건 저 위에와 같이 client쪽에서 임시로 이 문제를 해결하고 product에서는 빼는게 좋을거같다.
product까지 가진않을거같지만.
